builds:
  - binary: itdns
    id: "itdns"
    main: ./
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
  - binary: itdnsctl
    id: "itdnsctl"
    main: ./itdnsctl/
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
dockers:
  - goos: linux
    goarch: amd64
    goarm: ''
    binaries:
      - itdns
    skip_push: false
    dockerfile: Dockerfile
    image_templates:
    - "innovate/itdns:amd64-{{ .Tag }}"
    - "innovate/itdns:amd64-v{{ .Major }}"
    - innovate/itdns:amd64-latest
  - goos: linux
    goarch: amd64
    goarm: ''
    binaries:
      - itdnsctl
    skip_push: false
    dockerfile: Dockerfile.itdnsctl
    # Template of the docker tag. Defaults to `{{ .Version }}`.
    # Other allowed fields are:
    # - `.Commint`
    # - `.Tag`
    # - `.Major`
    # - `.Minor`
    # - `.Patch`
    # - `.Env.VARIABLE_NAME`
    image_templates:
    - "innovate/itdnsctl:amd64-{{ .Tag }}"
    - "innovate/itdnsctl:amd64-v{{ .Major }}"
    - innovate/itdnsctl:amd64-latest

  - goos: linux
    goarch: arm64
    goarm: ''
    binaries:
      - itdns
    skip_push: false
    dockerfile: Dockerfile
    image_templates:
    - "innovate/itdnsctl:arm64-{{ .Tag }}"
    - "innovate/itdnsctl:arm64-v{{ .Major }}"
    - innovate/itdnsctl:arm64-latest
  - goos: linux
    goarch: arm64
    goarm: ''
    binaries:
      - itdnsctl
    skip_push: false
    dockerfile: Dockerfile.itdnsctl
    image_templates:
    - "innovate/itdnsctl:arm64-{{ .Tag }}"
    - "innovate/itdnsctl:arm64-v{{ .Major }}"
    - innovate/itdnsctl:arm64-latest


  - goos: linux
    goarch: arm
    goarm: '6'
    binaries:
      - itdns
    skip_push: false
    dockerfile: Dockerfile
    image_templates:
    - "innovate/itdnsctl:armhf-{{ .Tag }}"
    - "innovate/itdnsctl:armhf-v{{ .Major }}"
    - innovate/itdnsctl:armhf-latest
  - goos: linux
    goarch: arm
    goarm: '6'
    binaries:
      - itdnsctl
    skip_push: false
    dockerfile: Dockerfile.itdnsctl
    image_templates:
    - "innovate/itdnsctl:armhf-{{ .Tag }}"
    - "innovate/itdnsctl:armhf-v{{ .Major }}"
    - innovate/itdnsctl:armhf-latest